
all:
	$(MAKE) byte-compile

byte-compile:
	$(MAKE) byte-compile -C auto-complete-1.3
#	$(MAKE) bytecompile -C yatex1.74
	$(MAKE) elc -C apel-10.7
	$(MAKE) bytecompile -C anything
	$(MAKE) lisp -C color-theme-6.6.0
	$(MAKE) bytecompile -C elscreen
	$(MAKE) bytecompile -C misc

