(require 'dircolors)

;; use dircolors in dired-mode
(font-lock-add-keywords
 'dired-mode
 (mapcar (lambda (x)
           (list
            (format "\\(%s\\)$"
                    (mapconcat (lambda (ext)
                                 (if (stringp ext)
                                     (format "\\.%s" ext)
                                   (format ".*%s.*" (cadr ext))))
                               (car x)
                               "\\|"))
            `(".+" (dired-move-to-filename) nil (0 ',(cadr x)))))
         dircolors-extension)) 

(defun my-style-set-dircolors-default ()
  (set-face-foreground 'dircolors-face-dir            "mediumblue"     )
  (set-face-foreground 'dircolors-face-text           "purple"         )
  (set-face-foreground 'dircolors-face-doc            "purple"         )
  (set-face-foreground 'dircolors-face-html           "magenta"        )
  (set-face-foreground 'dircolors-face-package        "firebrick"      )
  (set-face-foreground 'dircolors-face-tar            "firebrick"      )
  (set-face-foreground 'dircolors-face-dos            "darkred"        )
  (set-face-foreground 'dircolors-face-sound          "yellow"         )
  (set-face-foreground 'dircolors-face-img            "yellow"         )
  (set-face-foreground 'dircolors-face-ps             "brown"          )
  (set-face-foreground 'dircolors-face-backup         "darkslategrey"  )
  (set-face-foreground 'dircolors-face-make           "seagreen"       )
  (set-face-foreground 'dircolors-face-paddb          "Orange"         )
  (set-face-foreground 'dircolors-face-lang           "cyan"           )
  (set-face-foreground 'dircolors-face-emacs          "steelblue"      )
  (set-face-foreground 'dircolors-face-lang-interface "deepskyblue"    )
  (set-face-foreground 'dircolors-face-yacc           "dodgerblue"     )
  (set-face-foreground 'dircolors-face-objet          "orangered"      )
  (set-face-foreground 'dircolors-face-exec           "red"            )
  (set-face-foreground 'dircolors-face-asm            "Tan"            )
  (set-face-foreground 'dircolors-face-compress       "firebrick"      )
)

(defun my-style-set-dircolors-xemacs ()
  (set-face-foreground 'dircolors-face-dir            "Magenta"        )
  (set-face-foreground 'dircolors-face-doc            "MediumTurquoise")
  (set-face-foreground 'dircolors-face-html           "Plum"           )
  (set-face-foreground 'dircolors-face-package        "IndianRed"      )
  (set-face-foreground 'dircolors-face-tar            "OrangeRed"      )
  (set-face-foreground 'dircolors-face-dos            "LimeGreen"      )
  (set-face-foreground 'dircolors-face-sound          "DodgerBlue1"    )
  (set-face-foreground 'dircolors-face-img            "Salmon"         )
  (set-face-foreground 'dircolors-face-ps             "BlueViolet"     )
  (set-face-foreground 'dircolors-face-backup         "SkyBlue3"       )
  (set-face-foreground 'dircolors-face-make           "Khaki"          )
  (set-face-foreground 'dircolors-face-paddb          "Orange"         )
  (set-face-foreground 'dircolors-face-lang           "darkblue"       )
  (set-face-foreground 'dircolors-face-emacs          "GreenYellow"    )
  (set-face-foreground 'dircolors-face-lang-interface "brown"          )
  (set-face-foreground 'dircolors-face-yacc           "Coral"          )
  (set-face-foreground 'dircolors-face-objet          "DimGray"        )
  (set-face-foreground 'dircolors-face-asm            "Tan3"           )
  (set-face-foreground 'dircolors-face-compress       "Sienna"         )
  (set-face-foreground 'dircolors-face-script         "GreenYellow"    )
)

