;; (add-to-list 'auto-mode-alist '("\\.[sS]$" . asm-mode))
;; (setq asm-comment-char "#")
;; (add-hook 'asm-mode-hook
;; 	  '(lambda ()
;; 	     (setq asm-font-lock-keywords
;; 		   (append
;; 		    (list
;; 		     '("#.*$" . font-lock-comment-face)
;; 		     '("[ \t]'.+'[ \t\n,]" . font-lock-string-face)
;; 		     '("[\(\)\\,]" . font-lock-keyword-face)
;; 		     '("[, \t]#" . font-lock-variable-name-face)
;; 		     '("@"  . font-lock-reference-face)
;; 		     '("[^_0-9a-zA-Z][rR][0-7][hlHL][^_0-9a-zA-Z]" . font-lock-type-face)
;; 		     '("[^_0-9a-zA-Z][cCeEdD][pP][^_0-9a-zA-Z]" . font-lock-type-face)
;; 		     '("[^_0-9a-zA-Z][rR][0-7][^_0-9a-zA-Z]" . font-lock-string-face)
;; 		     '("[^_0-9a-zA-Z][sS][pP][^_0-9a-zA-Z]" . font-lock-string-face)
;; 		     '("[^_0-9a-zA-Z][cC][cC][^_0-9a-zA-Z]" . font-lock-type-face)
;; 		     '("[^_0-9a-zA-Z][dD][bB][^_0-9a-zA-Z]" . font-lock-keyword-face)
;; 		     '("[^_0-9a-zA-Z][bB][cC][cC][^_0-9a-zA-Z]" . font-lock-keyword-face)
;; 		     '("\\.[bB][ \t]" . font-lock-type-face)
;; 		     '("\\.[wW][ \t]" . font-lock-string-face)
;; 		     '("^.+::" . font-lock-function-name-face)
;; 		     '("[0-9]+\\$" . font-lock-function-name-face)
;; 		     '("^[ \t]include[ \t]" . font-lock-keyword-face)
;; 		     '("[ \t]equ[ \t]" . font-lock-keyword-face)
;; 		     '("^[ \t]MEMPAGE[ \t]" . font-lock-keyword-face)
;; 		     '("^[ \t].+PP[ \t\n]" . font-lock-keyword-face)
;; 		     '("\$[a-z][a-z0-9]+" . font-lock-type-face)
;; 		     )
;; 		    asm-font-lock-keywords))))

(require 'gas-mode)
(add-to-list 'auto-mode-alist '("\\.[sS]$'" . gas-mode))
;;(setq gas-comment-char "#")

(add-hook 'asm-mode-hook
	  '(lambda ()
	     (setq gas-font-lock-keywords
		   (append
		    (list
		     '("#.*$" . font-lock-comment-face)
		     '("[ \t]'.+'[ \t\n,]" . font-lock-string-face)
		     '("[\(\)\\,]" . font-lock-keyword-face)
		     '("[, \t]#" . font-lock-variable-name-face)
		     '("@"  . font-lock-reference-face)
		     '("[^_0-9a-zA-Z][rR][0-7][hlHL][^_0-9a-zA-Z]" . font-lock-type-face)
		     '("[^_0-9a-zA-Z][cCeEdD][pP][^_0-9a-zA-Z]" . font-lock-type-face)
		     '("[^_0-9a-zA-Z][rR][0-7][^_0-9a-zA-Z]" . font-lock-string-face)
		     '("[^_0-9a-zA-Z][sS][pP][^_0-9a-zA-Z]" . font-lock-string-face)
		     '("[^_0-9a-zA-Z][cC][cC][^_0-9a-zA-Z]" . font-lock-type-face)
		     '("[^_0-9a-zA-Z][dD][bB][^_0-9a-zA-Z]" . font-lock-keyword-face)
		     '("[^_0-9a-zA-Z][bB][cC][cC][^_0-9a-zA-Z]" . font-lock-keyword-face)
		     '("\\.[bB][ \t]" . font-lock-type-face)
		     '("\\.[wW][ \t]" . font-lock-string-face)
		     '("^.+::" . font-lock-function-name-face)
		     '("[0-9]+\\$" . font-lock-function-name-face)
		     '("^[ \t]include[ \t]" . font-lock-keyword-face)
		     '("[ \t]equ[ \t]" . font-lock-keyword-face)
		     '("^[ \t]MEMPAGE[ \t]" . font-lock-keyword-face)
		     '("^[ \t].+PP[ \t\n]" . font-lock-keyword-face)
		     '("\$[a-z][a-z0-9]+" . font-lock-type-face)
		     )
		    gas-font-lock-keywords))))
